Switch back to fetching keys from a keyserver, but use multiple keyservers to handle edge cases better
Also, this modifies `update.sh` to ensure that several keyservers definitely have a copy of the public key we need.

This should account for flakiness in ha.pool.sks-keyservers.net, as well as flakiness in environments where the default HKP port is blocked (by explicitly trying to use other keyservers that listen on port 80).

diff --git a/Dockerfile.template b/Dockerfile.template
--- a/Dockerfile.template
+++ b/Dockerfile.template
@@ -16,18 +16,27 @@ ENV SOLR_UID 8983
 RUN groupadd -r -g $SOLR_UID $SOLR_USER && \
   useradd -r -u $SOLR_UID -g $SOLR_USER $SOLR_USER
 
-ENV SOLR_VERSION 0.0.0
-
 ENV SOLR_KEY "fingerprint-goes-here"
-ENV KEYS https://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/KEYS
+RUN echo "fetching GPG key $SOLR_KEY"; \
+  for server in \
+    ha.pool.sks-keyservers.net \
+    hkp://keyserver.ubuntu.com:80 \
+    hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu \
+  ; do \
+    echo "  trying $server"; \
+    if gpg --keyserver "$server" --recv-keys "$SOLR_KEY"; then \
+      exit 0; \
+    fi; \
+  done; \
+  echo >&2 "error: failed to fetch $SOLR_KEY from several disparate servers -- network issues?"; \
+  exit 1
 
+ENV SOLR_VERSION 0.0.0
 ENV SOLR_SHA256 "checksum-goes-here"
 ENV SOLR_URL ${SOLR_DOWNLOAD_SERVER:-https://archive.apache.org/dist/lucene/solr}/$SOLR_VERSION/solr-$SOLR_VERSION.tgz
 
 RUN mkdir -p /opt/solr && \
-  wget -nv $KEYS -O /opt/KEYS && \
-  gpg --import /opt/KEYS && \
-  rm /opt/KEYS && \
   wget -nv $SOLR_URL -O /opt/solr.tgz && \
   wget -nv $SOLR_URL.asc -O /opt/solr.tgz.asc && \
   echo "$SOLR_SHA256 */opt/solr.tgz" | sha256sum -c - && \
