Improve --user invocation with INIT_SOLR_HOME
- change solr-create/solr-demo to not use sentinel files but look for the core directory
- change start-local-solr to write the PID to the logs directory if needed
- change start-local-solr to use SOLR_OPTS to limit the first JVM start to localhost,
  instead of writing a config file
- patch the bin/solr script to use `id` instead of `whoami` so it does not complain about
  missing /etc/password entries for the current user
- patch the bin/solr script to invoke lsof so it does not complain about
  missing /etc/password entries for the current user
- remove an outdated comment
- add set -euo pipefail for improved safety

With these changes you can:

```
mkdir mysolrhome logs
docker run -it \
  --mount type=bind,source=$PWD/mysolrhome,destination=/mysolrhome \
  --mount type=bind,source=$PWD/logs,destination=/logs \
  -e VERBOSE=yes \
  -e SOLR_HOME=/mysolrhome \
  -e SOLR_LOGS_DIR=/logs \
  -e INIT_SOLR_HOME=yes \
  -u "$(id -u):$(id -g)" \
  solr solr-create -c books
```

diff --git a/6.5/scripts/solr-demo b/6.5/scripts/solr-demo
--- a/6.5/scripts/solr-demo
+++ b/6.5/scripts/solr-demo
@@ -2,19 +2,19 @@
 #
 # Configure a Solr demo and then run solr in the foreground
 
-set -e
+set -euo pipefail
 
-if [[ "$VERBOSE" = "yes" ]]; then
+if [[ "${VERBOSE:-}" = "yes" ]]; then
     set -x
 fi
 
 . /opt/docker-solr/scripts/run-initdb
 
-sentinel=/opt/docker-solr/demo_created
-if [ -f $sentinel ]; then
-  echo "skipping demo creation"
+CORE=demo
+CORE_DIR="${SOLR_HOME:-/opt/solr/server/solr}/demo"
+if [ -d "$CORE_DIR" ]; then
+  echo "$CORE_DIR exists; skipping demo creation"
 else
-  CORE=demo
   start-local-solr
   echo "Creating $CORE"
   /opt/solr/bin/solr create -c "$CORE"
@@ -25,7 +25,12 @@ else
   /opt/solr/bin/post -c $CORE example/exampledocs/books.csv
   echo "Loaded example data"
   stop-local-solr
-  touch $sentinel
+
+    # check the core_dir exists; otherwise the detecting above will fail after stop/start
+    if [ ! -d "$CORE_DIR" ]; then
+        echo "Missing $CORE_DIR"
+        exit 1
+    fi
 fi
 
 exec solr -f
