Revert "multistage build (#197)"
This reverts commit bbfaa1b560828203f0867eaa075bb8688785c652.

diff --git a/7.6/slim/Dockerfile b/7.6/slim/Dockerfile
--- a/7.6/slim/Dockerfile
+++ b/7.6/slim/Dockerfile
@@ -1,64 +1,78 @@
-### get debian with wget
-FROM debian:stretch-slim as our_debian
 
-RUN apt-get update
-RUN apt-get -y install wget gpg
-
-COPY builder_tools/* /builder_tools/
-
-
-### get, check and install solr and our scripts
-FROM our_debian AS solr_builder
+FROM openjdk:11-jre-slim
+MAINTAINER  Martijn Koster "mak-docker@greenhills.co.uk"
 
 # Override the solr download location with e.g.:
 #   docker build -t mine --build-arg SOLR_DOWNLOAD_SERVER=http://www-eu.apache.org/dist/lucene/solr .
 ARG SOLR_DOWNLOAD_SERVER
 
-ENV SOLR_VERSION="7.6.0"
-ENV SOLR_URL="${SOLR_DOWNLOAD_SERVER:-https://archive.apache.org/dist/lucene/solr}/7.6.0/solr-7.6.0.tgz"
-ENV SOLR_SHA256="2cb425a0b30ff153465d306803e514e53e41924d74f28d842cb3a07cace759d5"
-ENV SOLR_KEY="95B01F0E78111D63D331C1A751F0CC22F625308A"
+RUN apt-get update && \
+  apt-get -y install lsof procps wget gpg && \
+  rm -rf /var/lib/apt/lists/*
 
-RUN bash /builder_tools/get-gpg-keys.sh $SOLR_KEY
-RUN bash /builder_tools/get-solr.sh $SOLR_URL $SOLR_SHA256
-
-COPY scripts /opt/docker-solr/scripts
-
-
-### get and check gosu
-FROM our_debian AS gosu_builder
+ENV SOLR_USER="solr" \
+    SOLR_UID="8983" \
+    SOLR_GROUP="solr" \
+    SOLR_GID="8983" \
+    SOLR_VERSION="7.6.0" \
+    SOLR_URL="${SOLR_DOWNLOAD_SERVER:-https://archive.apache.org/dist/lucene/solr}/7.6.0/solr-7.6.0.tgz" \
+    SOLR_SHA256="2cb425a0b30ff153465d306803e514e53e41924d74f28d842cb3a07cace759d5" \
+    SOLR_KEYS="95B01F0E78111D63D331C1A751F0CC22F625308A" \
+    PATH="/opt/solr/bin:/opt/docker-solr/scripts:$PATH"
 
 ENV GOSU_VERSION 1.11
 ENV GOSU_KEY B42F6819007F00F88E364FD4036A9C25BF357DD4
 
-RUN bash /builder_tools/get-gpg-keys.sh $GOSU_KEY
-RUN bash /builder_tools/get-gosu.sh $GOSU_VERSION
-
-
-### Now prepare the solr image
-FROM openjdk:11-jre-slim
-
-LABEL maintainer="Martijn Koster \"mak-docker@greenhills.co.uk\""
-LABEL repository="https://github.com/docker-solr/docker-solr"
-
-ARG SOLR_USER="solr"
-ARG SOLR_UID="8983"
-ARG SOLR_GROUP="solr"
-ARG SOLR_GID="8983"
-
-ENV PATH="/opt/solr/bin:/opt/docker-solr/scripts:$PATH"
-
-RUN set -e; \
-  apt-get update; \
-  apt-get -y install lsof procps wget; \
-  rm -rf /var/lib/apt/lists/*; \
-  groupadd -r --gid $SOLR_GID $SOLR_GROUP; \
+RUN groupadd -r --gid $SOLR_GID $SOLR_GROUP && \
   useradd -r --uid $SOLR_UID --gid $SOLR_GID $SOLR_USER
 
-COPY --from=solr_builder --chown=solr:solr /opt /opt
-COPY --from=solr_builder --chown=solr:solr /docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
+RUN set -e; \
+  export GNUPGHOME="/tmp/gnupg_home" && \
+  mkdir -p "$GNUPGHOME" && \
+  chmod 700 "$GNUPGHOME" && \
+  for key in $SOLR_KEYS $GOSU_KEY; do \
+    found=''; \
+    for server in \
+      ha.pool.sks-keyservers.net \
+      hkp://keyserver.ubuntu.com:80 \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      pgp.mit.edu \
+    ; do \
+      echo "  trying $server for $key"; \
+      gpg --batch --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch $key from several disparate servers -- network issues?" && exit 1; \
+  done; \
+  exit 0
 
-COPY --from=gosu_builder /usr/local/bin/gosu /usr/local/bin/gosu
+RUN set -e; \
+  export GNUPGHOME="/tmp/gnupg_home" && \
+  dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" && \
+  wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch" && \
+  wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc" && \
+  gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && \
+  rm /usr/local/bin/gosu.asc && \
+  chmod +x /usr/local/bin/gosu && \
+  gosu nobody true && \
+  mkdir -p /opt/solr && \
+  echo "downloading $SOLR_URL" && \
+  wget -nv $SOLR_URL -O /opt/solr.tgz && \
+  echo "downloading $SOLR_URL.asc" && \
+  wget -nv $SOLR_URL.asc -O /opt/solr.tgz.asc && \
+  echo "$SOLR_SHA256 */opt/solr.tgz" | sha256sum -c - && \
+  (>&2 ls -l /opt/solr.tgz /opt/solr.tgz.asc) && \
+  gpg --batch --verify /opt/solr.tgz.asc /opt/solr.tgz && \
+  tar -C /opt/solr --extract --file /opt/solr.tgz --strip-components=1 && \
+  rm /opt/solr.tgz* && \
+  rm -Rf /opt/solr/docs/ && \
+  mkdir -p /opt/solr/server/solr/lib /opt/solr/server/solr/mycores /opt/solr/server/logs /docker-entrypoint-initdb.d /opt/docker-solr /opt/mysolrhome && \
+  sed -i -e 's/"\$(whoami)" == "root"/$(id -u) == 0/' /opt/solr/bin/solr && \
+  sed -i -e 's/lsof -PniTCP:/lsof -t -PniTCP:/' /opt/solr/bin/solr && \
+  sed -i -e '/-Dsolr.clustering.enabled=true/ a SOLR_OPTS="$SOLR_OPTS -Dsun.net.inetaddr.ttl=60 -Dsun.net.inetaddr.negative.ttl=60"' /opt/solr/bin/solr.in.sh && \
+  chown -R $SOLR_USER:$SOLR_GROUP /opt/solr
+
+COPY scripts /opt/docker-solr/scripts
+RUN chown -R $SOLR_USER:$SOLR_GROUP /opt/docker-solr /opt/mysolrhome
 
 EXPOSE 8983
 WORKDIR /opt/solr
