Make solr port configurable (#163)
Remove the SOLR_PORT sed in solr.in.sh from the Dockerfiles.
Report bad SOLR_PORT values in our scripts.
Use SOLR_PORT in our scripts, if set.
In the docker-entrypoint.sh, reset SOLR_PORT to the default if it is non-numeric (which can happen in kubernetes in certain circumstances)
Add a test specifying SOLR_PORT as an environment variable for docker run.

diff --git a/5.5/alpine/scripts/solr-foreground b/5.5/alpine/scripts/solr-foreground
--- a/5.5/alpine/scripts/solr-foreground
+++ b/5.5/alpine/scripts/solr-foreground
@@ -9,6 +9,11 @@ fi
 
 . /opt/docker-solr/scripts/run-initdb
 
+if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT}"; then
+  echo "Invalid SOLR_PORT=$SOLR_PORT environment variable specified"
+  exit 1
+fi
+
 echo "Starting Solr $SOLR_VERSION"
 
 exec solr -f "$@"
diff --git a/7.2/alpine/scripts/solr-create b/7.2/alpine/scripts/solr-create
--- a/7.2/alpine/scripts/solr-create
+++ b/7.2/alpine/scripts/solr-create
@@ -32,6 +32,11 @@ if [[ -z "${CORE_NAME:-}" ]]; then
   exit 1
 fi
 
+if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"$SOLR_PORT"; then
+  echo "Invalid SOLR_PORT=$SOLRT_PORT environment variable specified"
+  exit 1
+fi
+
 # cores get created in SOLR_HOME
 CORE_DIR="${SOLR_HOME:-/opt/solr/server/solr}/$CORE_NAME"
 
@@ -45,7 +50,7 @@ else
 
     # See https://github.com/docker-solr/docker-solr/issues/27
     echo "Checking core"
-    if ! wget -O - 'http://localhost:8983/solr/admin/cores?action=STATUS' | grep -q instanceDir; then
+    if ! wget -O - "http://localhost:${SOLR_PORT:-8983}/solr/admin/cores?action=STATUS" | grep -q instanceDir; then
       echo "Could not find any cores"
       exit 1
     fi
diff --git a/7.2/alpine/scripts/start-local-solr b/7.2/alpine/scripts/start-local-solr
--- a/7.2/alpine/scripts/start-local-solr
+++ b/7.2/alpine/scripts/start-local-solr
@@ -28,6 +28,11 @@ if [ -z "${MY_SOLR_PID_DIR:-}" ]; then
     fi
 fi
 
+if [[ -v SOLR_PORT ]] && ! grep -E -q '^[0-9]+$' <<<"${SOLR_PORT:-}"; then
+  echo "Invalid SOLR_PORT=$SOLR_PORT environment variable specified"
+  exit 1
+fi
+
 echo "Running solr in the background. Logs are in $MY_SOLR_LOGS_DIR"
 SOLR_OPTS=$MY_SOLR_OPTS solr start
 max_try=${MAX_TRY:-12}
