Keep track of known keys, support multiple sigs, ownertrust

diff --git a/5.5/Dockerfile b/5.5/Dockerfile
--- a/5.5/Dockerfile
+++ b/5.5/Dockerfile
@@ -17,17 +17,26 @@ RUN groupadd -r -g $SOLR_UID $SOLR_USER && \
   useradd -r -u $SOLR_UID -g $SOLR_USER $SOLR_USER
 
 ENV SOLR_VERSION 5.5.4
-
-ENV SOLR_KEY E6E21FFCDCEA14C95910EA65051A0FAF76BC6507
-ENV KEYS https://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/KEYS
-
-ENV SOLR_SHA256 c1528e4afc9a0b8e7e5be0a16f40bb4080f410d502cd63b4447d448c49e9f500
 ENV SOLR_URL ${SOLR_DOWNLOAD_SERVER:-https://archive.apache.org/dist/lucene/solr}/$SOLR_VERSION/solr-$SOLR_VERSION.tgz
+ENV SOLR_SHA256 c1528e4afc9a0b8e7e5be0a16f40bb4080f410d502cd63b4447d448c49e9f500
+ENV SOLR_KEYS E6E21FFCDCEA14C95910EA65051A0FAF76BC6507
+
+RUN set -ex; for key in $SOLR_KEYS; do \
+    found=''; \
+    for server in \
+      ha.pool.sks-keyservers.net \
+      hkp://keyserver.ubuntu.com:80 \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      pgp.mit.edu \
+    ; do \
+      echo "  trying $server for $key"; \
+      gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch $key from several disparate servers -- network issues?" && exit 1; \
+  done; \
+  exit 0
 
 RUN mkdir -p /opt/solr && \
-  wget -nv $KEYS -O /opt/KEYS && \
-  gpg --import /opt/KEYS && \
-  rm /opt/KEYS && \
   wget -nv $SOLR_URL -O /opt/solr.tgz && \
   wget -nv $SOLR_URL.asc -O /opt/solr.tgz.asc && \
   echo "$SOLR_SHA256 */opt/solr.tgz" | sha256sum -c - && \
diff --git a/6.4/alpine/Dockerfile b/6.4/alpine/Dockerfile
--- a/6.4/alpine/Dockerfile
+++ b/6.4/alpine/Dockerfile
@@ -22,17 +22,26 @@ RUN addgroup -S -g $SOLR_UID $SOLR_USER && \
   adduser -S -u $SOLR_UID -g $SOLR_USER $SOLR_USER
 
 ENV SOLR_VERSION 6.4.2
-
-ENV SOLR_KEY 2085660D9C1FCCACC4A479A3BF160FF14992A24C
-ENV KEYS https://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/KEYS
-
-ENV SOLR_SHA256 354e1affd9cad7d6e86cde8c03aaeb604876f0764129621d8e231cdb35b31c55
 ENV SOLR_URL ${SOLR_DOWNLOAD_SERVER:-https://archive.apache.org/dist/lucene/solr}/$SOLR_VERSION/solr-$SOLR_VERSION.tgz
+ENV SOLR_SHA256 354e1affd9cad7d6e86cde8c03aaeb604876f0764129621d8e231cdb35b31c55
+ENV SOLR_KEYS 2085660D9C1FCCACC4A479A3BF160FF14992A24C 2085660D9C1FCCACC4A479A3BF160FF14992A24C
+
+RUN set -ex; for key in $SOLR_KEYS; do \
+    found=''; \
+    for server in \
+      ha.pool.sks-keyservers.net \
+      hkp://keyserver.ubuntu.com:80 \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      pgp.mit.edu \
+    ; do \
+      echo "  trying $server for $key"; \
+      gpg --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$key" && found=yes && break; \
+    done; \
+    test -z "$found" && echo >&2 "error: failed to fetch $key from several disparate servers -- network issues?" && exit 1; \
+  done; \
+  exit 0
 
 RUN mkdir -p /opt/solr && \
-  wget -nv $KEYS -O /opt/KEYS && \
-  gpg --import /opt/KEYS && \
-  rm /opt/KEYS && \
   echo "downloading $SOLR_URL" && \
   wget -q $SOLR_URL -O /opt/solr.tgz && \
   echo "downloading $SOLR_URL.asc" && \
